services:
  db:
    container_name: "{{ cookiecutter.docker_name_prefix }}-db-dev"
    image: postgres:18-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5400:5432"
    restart: unless-stopped
    env_file:
      - .env

  web:
    build: .
    container_name: "{{ cookiecutter.docker_name_prefix }}-web-dev"
    entrypoint: /app/scripts/entrypoint.sh
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.dev
    volumes:
     - app_data:/app/cdn
    ports:
      - "8005:8000"
    depends_on:
      - db
    restart: unless-stopped
    env_file:
      - .env

volumes:
  postgres_data:
  app_data:
