# Generated by Django 6.0.2 on 2026-03-26 20:05

import account.managers
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", account.managers.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="restored_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="Restored At"),
        ),
        migrations.AddField(
            model_name="user",
            name="transaction_id",
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name="Transaction ID"),
        ),
    ]
