# Generated by Django 6.0.2 on 2026-03-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_alter_user_managers_user_restored_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="restored_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Restored At"),
        ),
        migrations.AlterField(
            model_name="user",
            name="transaction_id",
            field=models.UUIDField(blank=True, null=True, verbose_name="Transaction ID"),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated At"),
        ),
    ]
